services:
  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: chat_app_db
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:


